#!/bin/bash

## REPOS
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
sudo add-apt-repository ppa:webupd8team/sublime-text-3 -y
sudo add-apt-repository ppa:ricotz/docky -y 
sudo add-apt-repository ppa:tiheum/equinox -y 
sudo add-apt-repository ppa:chris-lea/node.js -y
sudo add-apt-repository ppa:webupd8team/java -y

## UPDATE APT REPOS LIST
sudo apt-get update

## INSTALL
sudo apt-get install terminator vlc python-software-properties python g++ rar make curl sublime-text-installer plank faenza-icon-theme nodejs tasksel google-chrome-stable ttf-mscorefonts-installer inkscape gimp unity-tweak-tool samba git git-core oracle-java7-installer vim -y

## INSTALL LAMP-SERVER
sudo tasksel install lamp-server
sudo apt-get install php5-gd php5-curl php5-xdebug
sudo chmod 777 /var/www
sudo a2enmod rewrite
sudo sh -c 'curl https://raw.github.com/brunoziie/ubuntu_1304_cfg/master/apache_default_site.conf > /etc/apache2/sites-available/default'
sudo sh -c 'echo "ServerName localhost" >> /etc/apache2/conf.d/name'
sudo service apache2 restart


cd /var/www
wget https://github.com/brunoziie/ubuntu_1304_cfg/raw/master/adminer.php
wget https://raw.github.com/vrana/adminer/master/designs/haeckel/adminer.css

## ORTHER CONFIGS
sudo sh -c 'echo "enabled=0" > /etc/default/apport' && sudo service apport stop

## SETTING UP SUBLIME TEXT CONFIGS
cd /usr/local/share/fonts
sudo wget https://github.com/brunoziie/ubuntu_1304_cfg/raw/master/Monaco.ttf

cd ~/.config/sublime-text-3/Packages 
git clone https://github.com/wbond/sublime_package_control.git "Package Control"
cd "Package Control"
git checkout python3

echo '{"font_face": "Monaco", "font_size": 8}' > ./User/Preferences.sublime-settings
echo '[{ "keys": ["ctrl+shift+o"], "command": "goto_definition" }]' > ./User/Default\ \(Linux\).sublime-keymap

## SET BASH ALIAS
echo 'alias gc="git commit -am"' >> ~/.bashrc
echo 'alias gp="git pull && git push"' >> ~/.bashrc
echo 'alias www="cd /var/www"' >> ~/.bashrc

## INSTALL SYSTEM UPDATES
sudo apt-get upgrade -y 
sudo apt-get clean -y
